### ISSUE TITLE
Help with the while loop

### ISSUE THREAD

**Issue by UnstoppableGeek1** [geekcomputers/Python#732] opened 2020-05-11 06:00 UTC
I only want this while loop to run when word1 is a string but it also runs when I enter a integer. Does anyone know how to make it throw an error when I enter a number but continue running as long as I enter a string. That is why I added the while loop in the first place.

Here is the code:

while word1 != number:
		word1 = input("Enter a word: ")
		print(word1)
		print("There are,",len(word1), "letters in", word1)

**Comment by atharvakadlag** [comment] 2020-05-11 07:09
use `isinstance(<var>, <type>)` to check if the var is instance of class type
Eg.
```py
while isinstance(word1, int):
    word1 = input("Enter a word:")
    print(word1)
    print("There are",len(word1),"letters in",word1)
```

**Comment by UnstoppableGeek1** [comment] 2020-05-11 08:34
That did not work 

It said word1 is not defined 
But even when I define word1 = str(word1) before the while loop and also change the type Int  in isinstance function to str since i only want it to count the letters in words it still counts numbers as letters even though i want it to tell me there is an error. I want it to do this so I can eventually make it say in the code that it is a number and to try again. 

This is the code that i tried, but it did not work

word1 = str(word1)
while isinstance(word1, str):
	word1 = input("Enter a word:")
	print(word1)
	print("There are",len(word1),"letters in",word1)

**Comment by ravikumar0403** [comment] 2020-05-11 09:26
This can be done by using try except block. This is what I tried. Let me know if you get some more efficient solution.

`word=""  #define an empty string
while True:
	word = input("Enter the word: ")
	try:
		int(word) #converts word to integer if it contains only numbers. If not execute the except block of code
		print(word,"is integer")
		break
	except:
		print(word)
`

**Comment by ravikumar0403** [comment] 2020-05-11 09:37
This can be done by using try except block. This is what I tried. Let me know if you find any other efficient way to do it.

```python
word=""   #define an empty string
while True:
	word = input("Enter the word: ")
	try:
		int(word)  #convert the word to integer if only numbers are present else it will jump to except block of code
		print(word,"is integer")
		break
	except:
		print(word)
```

**Comment by atharvakadlag** [comment] 2020-05-11 13:14
> That did not work
> 
> It said word1 is not defined
> But even when I define word1 = str(word1) before the while loop and also change the type Int in isinstance function to str since i only want it to count the letters in words it still counts numbers as letters even though i want it to tell me there is an error. I want it to do this so I can eventually make it say in the code that it is a number and to try again.
> 
> This is the code that i tried, but it did not work
> 
> word1 = str(word1)
> while isinstance(word1, str):
> word1 = input("Enter a word:")
> print(word1)
> print("There are",len(word1),"letters in",word1)

i expected that you had already taken the first input
try this:
```py
word1 = ""
while isinstance(word1, int):
    word1 = input("Enter a word:")
    print(word1)
    print("There are",len(word1),"letters in",word1)
```

**Comment by ravikumar0403** [comment] 2020-05-11 13:46
> > That did not work
> > It said word1 is not defined
> > But even when I define word1 = str(word1) before the while loop and also change the type Int in isinstance function to str since i only want it to count the letters in words it still counts numbers as letters even though i want it to tell me there is an error. I want it to do this so I can eventually make it say in the code that it is a number and to try again.
> > This is the code that i tried, but it did not work
> > word1 = str(word1)
> > while isinstance(word1, str):
> > word1 = input("Enter a word:")
> > print(word1)
> > print("There are",len(word1),"letters in",word1)
> 
> i expected that you had already taken the first input
> try this:
> 
> ```python
> word1 = ""
> while isinstance(word1, int):
>     word1 = input("Enter a word:")
>     print(word1)
>     print("There are",len(word1),"letters in",word1)
> ```

"while isinstance(word1, int)" will return True if we pass an integer and reutrns
 False with word1 being empty string.
which means the while loop will never execute.

**Comment by UnstoppableGeek1** [comment] 2020-05-11 16:54
What is the difference between the try, except command and an if and else statement

**Comment by ravikumar0403** [comment] 2020-05-11 17:04
If statement works on conditional statements...
It will check a condition, if the condition is true, the if block of code is executed otherwise else block will be executed.

Whereas, try and except is used to handle errors. If you think a line/block of code can cause errors then you include that code in try block. When the code causes error, the code won't stop it's execution. Instead it skips the try block and jumps to the except block.

input() reads everything as a string so even if you enter 1234 it will be treated as string. We use int(1234) to convert it to integer. 
But what if we pass a character to int(), it will throw an error.

So we use put that block of code in try to avoid the error if a character is present in the string. If only numbers bare present. It will run without errors by skipping the except part of code.

Hope it helps

**Comment by republic-of-hackers** [comment] 2020-05-15 21:38
while True:
    word1 = input("Enter a word: ")
    try:
        int(word1)
        break
    except ValueError:
        print(word1)
        print("There are", len(word1), "letters in", word1)

Hope this is close to your expectations......

**Comment by republic-of-hackers** [comment] 2020-05-15 21:40
> use `isinstance(<var>, <type>)` to check if the var is instance of class type
> Eg.
> 
> ```python
> while isinstance(word1, int):
>     word1 = input("Enter a word:")
>     print(word1)
>     print("There are",len(word1),"letters in",word1)
> ```

When we input integer in this it consider it as the string and isinstance(word1, int) return false. isinstance(*,*) can't be used here in any way.

**Comment by atharvakadlag** [comment] 2020-05-16 05:01
> > use `isinstance(<var>, <type>)` to check if the var is instance of class type
> > Eg.
> > ```python
> > while isinstance(word1, int):
> >     word1 = input("Enter a word:")
> >     print(word1)
> >     print("There are",len(word1),"letters in",word1)
> > ```
> 
> When we input integer in this it consider it as the string and isinstance(word1, int) return false. isinstance(_,_) can't be used here in any way.
To put a number in word1, you need to do 
```word1 = int(input('Enter the word: '))

**Comment by republic-of-hackers** [comment] 2020-05-16 07:33
> > > use `isinstance(<var>, <type>)` to check if the var is instance of class type
> > > Eg.
> > > ```python
> > > while isinstance(word1, int):
> > >     word1 = input("Enter a word:")
> > >     print(word1)
> > >     print("There are",len(word1),"letters in",word1)
> > > ```
> > 
> > 
> > When we input integer in this it consider it as the string and isinstance(word1, int) return false. isinstance(_,_) can't be used here in any way.
> 
> To put a number in word1, you need to do

It doesn't put the integer in word1 but check wheather the instance created in word1 is int or not, as not returns false.
![Capture](https://user-images.githubusercontent.com/30999716/82113701-9f6e5f80-9775-11ea-8ded-95d7a22291e6.JPG)

**Comment by atharvakadlag** [comment] 2020-05-17 06:20
![Screenshot 2020-05-17 at 11 50 24 AM](https://user-images.githubusercontent.com/59139103/82137325-a1e3be80-9834-11ea-96d7-530551829225.png)

**Comment by gepcel** [comment] 2020-05-18 01:15
I'm exactly sure what you want. Try this:

```
In [2]: word1 = input()
10

In [3]: word1
Out[3]: '10'

In [4]: word1.isdigit()
Out[4]: True

In [5]: word1 = input()
hello

In [6]: word1
Out[6]: 'hello'

In [7]: word1.isdigit()
Out[7]: False
```

**Comment by republic-of-hackers** [comment] 2020-05-18 16:01
I think the Issue is resolved and should be closed by the owner.

**Closed** 2020-05-18 16:15 UTC
